---
  - hosts: master
    become: no
    gather_facts: no

    roles:
      - keyscan

  - hosts: slave
    become: yes
    gather_facts: no
    remote_user: vagrant

    roles:
      - addkey

  - hosts: all
    become: yes
    gather_facts: no

    roles:
      - user_hadoop
