---
# Password is hadoop
- name: create hadoop user
  user: name=hadoop append=yes groups=sudo
        shell=/bin/bash generate_ssh_key=yes ssh_key_bits=2048
        password=$6$OTLeHguf$zjrBqd2TZDjN9vSt0mocgtu/jLuxuoPFVSYP5WOINg1jkxHkVAlVZa1IuDnoCG5JMhawTPT/1i5x4U9lYsqvX1

- name: Allow group sudo to sudo without pass
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'

- name: install java
  apt: name=default-jre update_cache=no

- name: Add env var for JAVA
  lineinfile:
    dest: /home/hadoop/.bashrc
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^export JAVA_HOME.*', line: 'export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64' }
    - { regexp: '^export PATH.*JAVA_HOME', line: 'export PATH=$PATH:$JAVA_HOME/bin' }
