---
- name: Write core-site.xml
  template: src=core-site.xml.j2 dest=/opt/hadoop/etc/hadoop/core-site.xml

- name: Write hdfs-site.xml
  template: src=hdfs-site.xml.j2 dest=/opt/hadoop/etc/hadoop/hdfs-site.xml

- name: Write mapred-site.xml
  template: src=mapred-site.xml.j2 dest=/opt/hadoop/etc/hadoop/mapred-site.xml

- name: Write mapred-site.xml
  template: src=yarn-site.xml.j2 dest=/opt/hadoop/etc/hadoop/yarn-site.xml

- name: Write masters
  template: src=masters.j2 dest=/opt/hadoop/etc/hadoop/masters

- name: get slaves
  command: sed '1,/slave/d' /vagrant/inventory.ini
  register: slaves
  changed_when: False

- name: Write file slaves
  copy: content={{ slaves.stdout }} dest=/opt/hadoop/etc/hadoop/slaves

- name: add Java home
  lineinfile: dest=/opt/hadoop/etc/hadoop/hadoop-env.sh
              line="export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64"
              regexp="^export JAVA_HOME"

- name: Hadoop heap size
  lineinfile: dest=/opt/hadoop/etc/hadoop/hadoop-env.sh
              line="export HADOOP_HEAPSIZE=512"
              regexp="^export HADOOP_HEAPSIZE"

- name: Host checking in hadoop-env
  lineinfile: dest=/opt/hadoop/etc/hadoop/hadoop-env.sh
              line="export HADOOP_SSH_OPTS=\"-oStrictHostKeyChecking=no\""
              regexp="^export HADOOP_SSH_OPTS"
